import io
import json
import logging
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE

logger = logging.getLogger(__name__)

class DOCReportGenerator:
    def __init__(self):
        pass

    def generate_chatbot_report(self, conversation_data, analysis_data=None):
        """Generate a professional DOC report from chatbot conversation"""
        try:
            doc = Document()

            # Set up document styles
            self._setup_styles(doc)

            # Report Header
            self._create_report_header(doc, conversation_data)

            # Executive Summary
            self._create_executive_summary(doc, conversation_data, analysis_data)

            # Conversation Timeline
            self._create_conversation_timeline(doc, conversation_data)

            # Security Analysis
            if analysis_data:
                self._create_security_analysis(doc, analysis_data)

            # Recommendations
            self._create_recommendations(doc, conversation_data)

            # Footer
            self._create_report_footer(doc)

            # Save to BytesIO
            buffer = io.BytesIO()
            doc.save(buffer)
            buffer.seek(0)
            return buffer.getvalue()

        except Exception as e:
            logger.error(f"Error generating DOC report: {str(e)}")
            raise

    def _setup_styles(self, doc):
        """Setup custom styles for professional cybersecurity reports"""
        # Title style
        title_style = doc.styles.add_style('ReportTitle', WD_STYLE_TYPE.PARAGRAPH)
        title_style.font.size = Pt(24)
        title_style.font.bold = True
        title_style.font.color.rgb = RGBColor(0, 0, 139)  # Dark blue
        title_style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_style.paragraph_format.space_after = Pt(30)

        # Section header style
        section_style = doc.styles.add_style('SectionHeader', WD_STYLE_TYPE.PARAGRAPH)
        section_style.font.size = Pt(16)
        section_style.font.bold = True
        section_style.font.color.rgb = RGBColor(139, 0, 0)  # Dark red
        section_style.paragraph_format.space_after = Pt(15)

        # Cyber alert style
        alert_style = doc.styles.add_style('CyberAlert', WD_STYLE_TYPE.PARAGRAPH)
        alert_style.font.size = Pt(12)
        alert_style.font.bold = True
        alert_style.font.color.rgb = RGBColor(255, 0, 0)  # Red
        alert_style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Timestamp style
        timestamp_style = doc.styles.add_style('Timestamp', WD_STYLE_TYPE.PARAGRAPH)
        timestamp_style.font.size = Pt(10)
        timestamp_style.font.color.rgb = RGBColor(128, 128, 128)  # Gray
        timestamp_style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.RIGHT

    def _create_report_header(self, doc, conversation_data):
        """Create professional report header"""
        # Title
        title = doc.add_paragraph("SECURITY INCIDENT ANALYSIS REPORT", style='ReportTitle')

        # Report metadata table
        table = doc.add_table(rows=5, cols=2)
        table.style = 'Table Grid'

        # Set column widths
        table.columns[0].width = Inches(2)
        table.columns[1].width = Inches(4)

        # Header row
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Report Generated:'
        hdr_cells[1].text = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        # Data rows
        rows_data = [
            ['Classification:', 'CONFIDENTIAL'],
            ['Generated By:', 'SOAR SOC Assistant'],
            ['Report Type:', 'Chatbot Analysis Report'],
            ['Conversation ID:', conversation_data.get('id', 'N/A')]
        ]

        for i, (label, value) in enumerate(rows_data, 1):
            row_cells = table.rows[i].cells
            row_cells[0].text = label
            row_cells[1].text = value

        doc.add_paragraph()  # Spacer

        # Security classification banner
        alert = doc.add_paragraph("⚠️ CONFIDENTIAL - SECURITY INCIDENT REPORT ⚠️", style='CyberAlert')
        doc.add_paragraph()  # Spacer

    def _create_executive_summary(self, doc, conversation_data, analysis_data):
        """Create executive summary section"""
        # Section header
        header = doc.add_paragraph("EXECUTIVE SUMMARY", style='SectionHeader')

        # Summary content
        messages = conversation_data.get('messages', [])
        user_messages = len([msg for msg in messages if msg.get('sender') == 'user'])
        assistant_messages = len([msg for msg in messages if msg.get('sender') == 'assistant'])

        summary_text = f"""
This report contains the analysis of a security investigation conducted through the SOAR SOC Chatbot.
The conversation involved {user_messages} user queries and {assistant_messages} assistant responses.
"""

        if analysis_data:
            threats = len(analysis_data.get('threats', []))
            recommendations = len(analysis_data.get('recommendations', []))
            summary_text += f" Key findings include {threats} identified threats and {recommendations} security recommendations."

        summary = doc.add_paragraph(summary_text)
        summary.paragraph_format.space_after = Pt(15)

    def _create_conversation_timeline(self, doc, conversation_data):
        """Create conversation timeline section"""
        # Section header
        header = doc.add_paragraph("CONVERSATION TIMELINE", style='SectionHeader')

        messages = conversation_data.get('messages', [])

        for i, message in enumerate(messages):
            # Message header
            sender = message.get('sender', 'unknown').upper()
            timestamp = message.get('timestamp', datetime.now())
            if isinstance(timestamp, str):
                try:
                    timestamp = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
                except:
                    timestamp = datetime.now()

            msg_header = doc.add_paragraph(f"{sender} - {timestamp.strftime('%H:%M:%S')}", style='Timestamp')

            # Message content
            content = message.get('content', '')
            content_para = doc.add_paragraph(content)
            content_para.paragraph_format.space_after = Pt(6)

            # Actions if present
            actions = message.get('actions', [])
            if actions:
                actions_text = "Available Actions: " + ", ".join([action.get('label', '') for action in actions])
                actions_para = doc.add_paragraph(actions_text)
                actions_para.paragraph_format.space_after = Pt(6)

            # Data if present
            data = message.get('data', {})
            if data:
                data_json = json.dumps(data, indent=2)
                data_para = doc.add_paragraph(f"Data:\n{data_json}")
                data_para.paragraph_format.space_after = Pt(6)

            # Spacer between messages
            doc.add_paragraph()

            # Add page break every 10 messages
            if i > 0 and i % 10 == 0:
                doc.add_page_break()

    def _create_security_analysis(self, doc, analysis_data):
        """Create security analysis section"""
        # Section header
        header = doc.add_paragraph("SECURITY ANALYSIS", style='SectionHeader')

        # Threats table
        threats = analysis_data.get('threats', [])
        if threats:
            table = doc.add_table(rows=len(threats) + 1, cols=3)
            table.style = 'Table Grid'

            # Set column widths
            table.columns[0].width = Inches(2)
            table.columns[1].width = Inches(1.5)
            table.columns[2].width = Inches(3)

            # Header row
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'Threat Type'
            hdr_cells[1].text = 'Severity'
            hdr_cells[2].text = 'Description'

            # Data rows
            for i, threat in enumerate(threats, 1):
                row_cells = table.rows[i].cells
                row_cells[0].text = threat.get('type', 'Unknown')
                row_cells[1].text = threat.get('severity', 'Medium')
                row_cells[2].text = threat.get('description', 'No description')

            doc.add_paragraph()  # Spacer

    def _create_recommendations(self, doc, conversation_data):
        """Create recommendations section"""
        # Section header
        header = doc.add_paragraph("RECOMMENDATIONS", style='SectionHeader')

        recommendations = [
            "Implement the suggested security actions from the conversation",
            "Review and update security policies based on identified threats",
            "Monitor the affected systems for any suspicious activity",
            "Conduct a comprehensive security assessment of the environment",
            "Ensure all security tools are properly configured and updated"
        ]

        for rec in recommendations:
            rec_para = doc.add_paragraph(f"• {rec}")
            rec_para.paragraph_format.space_after = Pt(6)

    def _create_report_footer(self, doc):
        """Create report footer"""
        doc.add_paragraph()  # Spacer

        # Footer text
        footer_text = """
This report was generated automatically by the SOAR SOC Assistant.
For questions or concerns, please contact the security operations team.
"""

        footer = doc.add_paragraph(footer_text)
        footer.paragraph_format.space_after = Pt(15)

        # Generation timestamp
        timestamp = doc.add_paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", style='Timestamp')
