import io
import json
import logging
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.platypus.flowables import HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT

logger = logging.getLogger(__name__)

class PDFReportGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        """Setup custom styles for professional cybersecurity reports"""
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=colors.darkblue
        ))

        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceAfter=15,
            textColor=colors.darkred,
            borderColor=colors.darkred,
            borderWidth=1,
            borderPadding=5
        ))

        self.styles.add(ParagraphStyle(
            name='CyberAlert',
            parent=self.styles['Normal'],
            fontSize=12,
            textColor=colors.red,
            backgroundColor=colors.lightpink,
            borderColor=colors.red,
            borderWidth=1,
            borderPadding=5
        ))

        self.styles.add(ParagraphStyle(
            name='Timestamp',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.gray,
            alignment=TA_RIGHT
        ))

    def generate_chatbot_report(self, conversation_data, analysis_data=None):
        """Generate a professional SOC analyst-style PDF report from chatbot conversation"""
        try:
            buffer = io.BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=A4)
            story = []

            # Report Header
            story.extend(self._create_report_header())

            # Executive Summary
            story.extend(self._create_executive_summary(conversation_data, analysis_data))

            # Incident Timeline
            story.extend(self._create_incident_timeline(conversation_data))

            # Threat Analysis & MITRE ATT&CK Mapping
            story.extend(self._create_threat_analysis(conversation_data, analysis_data))

            # Impact Assessment
            story.extend(self._create_impact_assessment(conversation_data, analysis_data))

            # Response Actions
            story.extend(self._create_response_actions(conversation_data))

            # Evidence & Indicators
            story.extend(self._create_evidence_section(conversation_data))

            # Risk Assessment Matrix
            story.extend(self._create_risk_assessment(analysis_data))

            # Recommendations with Priority
            story.extend(self._create_detailed_recommendations(conversation_data, analysis_data))

            # Lessons Learned
            story.extend(self._create_lessons_learned(conversation_data))

            # Appendices
            story.extend(self._create_appendices(conversation_data, analysis_data))

            # Footer
            story.extend(self._create_report_footer())

            doc.build(story)
            buffer.seek(0)
            return buffer.getvalue()

        except Exception as e:
            logger.error(f"Error generating PDF report: {str(e)}")
            raise

    def _create_report_header(self):
        """Create professional report header"""
        elements = []

        # Title
        title = Paragraph("SECURITY INCIDENT ANALYSIS REPORT", self.styles['ReportTitle'])
        elements.append(title)
        elements.append(Spacer(1, 0.5*inch))

        # Report metadata
        metadata_table_data = [
            ['Report Generated:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
            ['Classification:', 'CONFIDENTIAL'],
            ['Generated By:', 'SOAR SOC Assistant'],
            ['Report Type:', 'Chatbot Analysis Report']
        ]

        metadata_table = Table(metadata_table_data, colWidths=[2*inch, 4*inch])
        metadata_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))

        elements.append(metadata_table)
        elements.append(Spacer(1, 0.5*inch))

        # Security classification banner
        classification = Paragraph("⚠️ CONFIDENTIAL - SECURITY INCIDENT REPORT ⚠️", self.styles['CyberAlert'])
        elements.append(classification)
        elements.append(Spacer(1, 0.3*inch))

        return elements

    def _create_executive_summary(self, conversation_data, analysis_data):
        """Create executive summary section"""
        elements = []

        # Section header
        header = Paragraph("EXECUTIVE SUMMARY", self.styles['SectionHeader'])
        elements.append(header)

        # Summary content
        summary_text = f"""
        This report contains the analysis of a security investigation conducted through the SOAR SOC Chatbot.
        The conversation involved {len([msg for msg in conversation_data.get('messages', []) if msg.get('sender') == 'user'])} user queries
        and {len([msg for msg in conversation_data.get('messages', []) if msg.get('sender') == 'assistant'])} assistant responses.
        """

        if analysis_data:
            summary_text += f" Key findings include {len(analysis_data.get('threats', []))} identified threats and {len(analysis_data.get('recommendations', []))} security recommendations."

        summary = Paragraph(summary_text, self.styles['Normal'])
        elements.append(summary)
        elements.append(Spacer(1, 0.3*inch))

        return elements

    def _create_incident_timeline(self, conversation_data):
        """Create incident timeline section with chronological analysis"""
        elements = []

        # Section header
        header = Paragraph("INCIDENT TIMELINE & CHRONOLOGY", self.styles['SectionHeader'])
        elements.append(header)

        messages = conversation_data.get('messages', [])

        # Create timeline table
        timeline_data = [['Time', 'Actor', 'Action/Event', 'Details']]

        for message in messages:
            sender = message.get('sender', 'unknown').upper()
            timestamp = message.get('timestamp', datetime.now())
            if isinstance(timestamp, str):
                timestamp = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))

            time_str = timestamp.strftime('%H:%M:%S')
            actor = 'SOC Analyst' if sender == 'USER' else 'AI Assistant'
            action = 'Query' if sender == 'USER' else 'Analysis/Response'
            details = message.get('content', '')[:100] + '...' if len(message.get('content', '')) > 100 else message.get('content', '')

            timeline_data.append([time_str, actor, action, details])

        timeline_table = Table(timeline_data, colWidths=[1*inch, 1.5*inch, 1.5*inch, 3*inch])
        timeline_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('BACKGROUND', (0, 1), (-1, -1), colors.lightgrey),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
        ]))

        elements.append(timeline_table)
        elements.append(Spacer(1, 0.3*inch))

        return elements

    def _create_threat_analysis(self, conversation_data, analysis_data):
        """Create threat analysis section with MITRE ATT&CK mapping"""
        elements = []

        # Section header
        header = Paragraph("THREAT ANALYSIS & MITRE ATT&CK MAPPING", self.styles['SectionHeader'])
        elements.append(header)

        # Extract potential threats from conversation
        messages = conversation_data.get('messages', [])
        threat_indicators = []

        for message in messages:
            content = message.get('content', '').lower()
            if any(keyword in content for keyword in ['malware', 'phishing', 'attack', 'breach', 'intrusion', 'exploit']):
                threat_indicators.append({
                    'type': 'Potential Threat Detected',
                    'description': message.get('content', '')[:200] + '...',
                    'confidence': 'Medium'
                })

        # Threats table
        if threat_indicators or (analysis_data and analysis_data.get('threats')):
            threat_data = [['Threat Type', 'MITRE Tactic', 'Severity', 'Description', 'Confidence']]

            # Add threats from analysis_data
            if analysis_data and analysis_data.get('threats'):
                for threat in analysis_data.get('threats', []):
                    threat_data.append([
                        threat.get('type', 'Unknown'),
                        threat.get('mitre_tactic', 'TBD'),
                        threat.get('severity', 'Medium'),
                        threat.get('description', 'No description'),
                        'High'
                    ])

            # Add threats from conversation analysis
            for threat in threat_indicators:
                threat_data.append([
                    threat['type'],
                    'Reconnaissance/Initial Access',
                    'Medium',
                    threat['description'],
                    threat['confidence']
                ])

            threat_table = Table(threat_data, colWidths=[1.5*inch, 1.5*inch, 1*inch, 2.5*inch, 0.8*inch])
            threat_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.darkred),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('BACKGROUND', (0, 1), (-1, -1), colors.lightgrey),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
            ]))

            elements.append(threat_table)
            elements.append(Spacer(1, 0.3*inch))

        return elements

    def _create_impact_assessment(self, conversation_data, analysis_data):
        """Create impact assessment section"""
        elements = []

        # Section header
        header = Paragraph("IMPACT ASSESSMENT", self.styles['SectionHeader'])
        elements.append(header)

        # Analyze conversation for impact indicators
        messages = conversation_data.get('messages', [])
        impact_indicators = {
            'data_breach': 0,
            'system_compromise': 0,
            'financial_loss': 0,
            'operational_disruption': 0
        }

        for message in messages:
            content = message.get('content', '').lower()
            if 'breach' in content or 'data loss' in content:
                impact_indicators['data_breach'] += 1
            if 'compromised' in content or 'hacked' in content:
                impact_indicators['system_compromise'] += 1
            if 'financial' in content or 'cost' in content:
                impact_indicators['financial_loss'] += 1
            if 'disruption' in content or 'downtime' in content:
                impact_indicators['operational_disruption'] += 1

        # Impact assessment table
        impact_data = [['Impact Category', 'Likelihood', 'Severity', 'Risk Level']]
        total_indicators = sum(impact_indicators.values())

        for category, count in impact_indicators.items():
            if count > 0:
                likelihood = 'High' if count > 2 else 'Medium' if count > 0 else 'Low'
                severity = 'High' if 'breach' in category or 'compromise' in category else 'Medium'
                risk_level = 'Critical' if likelihood == 'High' and severity == 'High' else 'High' if likelihood == 'High' or severity == 'High' else 'Medium'

                impact_data.append([
                    category.replace('_', ' ').title(),
                    likelihood,
                    severity,
                    risk_level
                ])

        if len(impact_data) > 1:
            impact_table = Table(impact_data, colWidths=[2*inch, 1.5*inch, 1.5*inch, 1.5*inch])
            impact_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.darkorange),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('BACKGROUND', (0, 1), (-1, -1), colors.lightgrey),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
            ]))

            elements.append(impact_table)
            elements.append(Spacer(1, 0.3*inch))

        return elements

    def _create_response_actions(self, conversation_data):
        """Create response actions section"""
        elements = []

        # Section header
        header = Paragraph("RESPONSE ACTIONS TAKEN", self.styles['SectionHeader'])
        elements.append(header)

        messages = conversation_data.get('messages', [])
        actions_taken = []

        for message in messages:
            if message.get('sender') == 'assistant':
                content = message.get('content', '').lower()
                if any(action in content for action in ['investigate', 'scan', 'block', 'quarantine', 'alert', 'notify']):
                    actions_taken.append({
                        'action': 'Security Investigation/Response',
                        'description': message.get('content', '')[:150] + '...',
                        'timestamp': message.get('timestamp', '')
                    })

        if actions_taken:
            action_data = [['Action Type', 'Description', 'Timestamp']]
            for action in actions_taken:
                action_data.append([
                    action['action'],
                    action['description'],
                    action['timestamp'][:19] if action['timestamp'] else 'N/A'
                ])

            action_table = Table(action_data, colWidths=[2*inch, 3*inch, 1.5*inch])
            action_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.darkgreen),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('BACKGROUND', (0, 1), (-1, -1), colors.lightgrey),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
            ]))

            elements.append(action_table)
            elements.append(Spacer(1, 0.3*inch))

        return elements

    def _create_evidence_section(self, conversation_data):
        """Create evidence and indicators section"""
        elements = []

        # Section header
        header = Paragraph("EVIDENCE & INDICATORS OF COMPROMISE (IOCs)", self.styles['SectionHeader'])
        elements.append(header)

        messages = conversation_data.get('messages', [])
        iocs = []

        for message in messages:
            content = message.get('content', '')
            # Extract potential IOCs
            if 'ip' in content.lower() and any(char.isdigit() for char in content):
                iocs.append({'type': 'IP Address', 'value': 'Potential IP found in conversation', 'source': 'Chat Analysis'})
            if 'hash' in content.lower():
                iocs.append({'type': 'File Hash', 'value': 'Hash mentioned in conversation', 'source': 'Chat Analysis'})
            if 'domain' in content.lower() or 'url' in content.lower():
                iocs.append({'type': 'Domain/URL', 'value': 'Domain/URL mentioned in conversation', 'source': 'Chat Analysis'})

        if iocs:
            ioc_data = [['IOC Type', 'Value', 'Source', 'Status']]
            for ioc in iocs:
                ioc_data.append([
                    ioc['type'],
                    ioc['value'],
                    ioc['source'],
                    'Under Investigation'
                ])

            ioc_table = Table(ioc_data, colWidths=[1.5*inch, 2.5*inch, 1.5*inch, 1.5*inch])
            ioc_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('BACKGROUND', (0, 1), (-1, -1), colors.lightgrey),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
            ]))

            elements.append(ioc_table)
            elements.append(Spacer(1, 0.3*inch))

        return elements

    def _create_risk_assessment(self, analysis_data):
        """Create risk assessment matrix section"""
        elements = []

        # Section header
        header = Paragraph("RISK ASSESSMENT MATRIX", self.styles['SectionHeader'])
        elements.append(header)

        # Risk matrix data
        risk_data = [
            ['Risk Level', 'Likelihood', 'Impact', 'Risk Score', 'Priority'],
            ['Critical', 'High', 'High', '9-10', 'Immediate Action'],
            ['High', 'High', 'Medium', '7-8', 'High Priority'],
            ['Medium', 'Medium', 'Medium', '4-6', 'Monitor Closely'],
            ['Low', 'Low', 'Low', '1-3', 'Low Priority']
        ]

        risk_table = Table(risk_data, colWidths=[1.5*inch, 1.5*inch, 1.5*inch, 1*inch, 1.5*inch])
        risk_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.darkred),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('BACKGROUND', (0, 1), (-1, -1), colors.lightgrey),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
        ]))

        elements.append(risk_table)
        elements.append(Spacer(1, 0.3*inch))

        return elements

    def _create_detailed_recommendations(self, conversation_data, analysis_data):
        """Create detailed recommendations with priority levels"""
        elements = []

        # Section header
        header = Paragraph("DETAILED RECOMMENDATIONS & MITIGATION STRATEGIES", self.styles['SectionHeader'])
        elements.append(header)

        recommendations = [
            {'priority': 'Critical', 'action': 'Implement immediate containment measures', 'timeline': 'Within 1 hour'},
            {'priority': 'High', 'action': 'Conduct comprehensive threat hunting', 'timeline': 'Within 4 hours'},
            {'priority': 'High', 'action': 'Review and update access controls', 'timeline': 'Within 24 hours'},
            {'priority': 'Medium', 'action': 'Enhance monitoring and alerting', 'timeline': 'Within 1 week'},
            {'priority': 'Medium', 'action': 'Conduct security awareness training', 'timeline': 'Within 2 weeks'},
            {'priority': 'Low', 'action': 'Perform post-incident review and lessons learned', 'timeline': 'Within 1 month'}
        ]

        rec_data = [['Priority', 'Recommendation', 'Timeline', 'Owner']]
        for rec in recommendations:
            rec_data.append([
                rec['priority'],
                rec['action'],
                rec['timeline'],
                'SOC Team'
            ])

        rec_table = Table(rec_data, colWidths=[1*inch, 3*inch, 1.5*inch, 1.5*inch])
        rec_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.darkgreen),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('BACKGROUND', (0, 1), (-1, -1), colors.lightgrey),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
        ]))

        elements.append(rec_table)
        elements.append(Spacer(1, 0.3*inch))

        return elements

    def _create_lessons_learned(self, conversation_data):
        """Create lessons learned section"""
        elements = []

        # Section header
        header = Paragraph("LESSONS LEARNED & IMPROVEMENT OPPORTUNITIES", self.styles['SectionHeader'])
        elements.append(header)

        lessons = [
            "Enhanced automated threat detection capabilities",
            "Improved incident response coordination",
            "Better integration between security tools",
            "Regular security training and awareness programs",
            "Continuous monitoring and threat intelligence updates"
        ]

        for lesson in lessons:
            lesson_para = Paragraph(f"• {lesson}", self.styles['Normal'])
            elements.append(lesson_para)
            elements.append(Spacer(1, 0.1*inch))

        return elements

    def _create_appendices(self, conversation_data, analysis_data):
        """Create appendices with raw data"""
        elements = []

        # Section header
        header = Paragraph("APPENDICES", self.styles['SectionHeader'])
        elements.append(header)

        # Appendix A: Full Conversation Log
        appendix_a = Paragraph("Appendix A: Complete Conversation Log", self.styles['SectionHeader'])
        elements.append(appendix_a)

        messages = conversation_data.get('messages', [])
        for i, message in enumerate(messages):
            sender = message.get('sender', 'unknown').upper()
            timestamp = message.get('timestamp', datetime.now())
            if isinstance(timestamp, str):
                timestamp = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))

            msg_text = f"[{timestamp.strftime('%H:%M:%S')}] {sender}: {message.get('content', '')}"
            msg_para = Paragraph(msg_text, self.styles['Normal'])
            elements.append(msg_para)
            elements.append(Spacer(1, 0.05*inch))

            if i > 0 and i % 5 == 0:
                elements.append(PageBreak())

        return elements

    def _create_recommendations(self, conversation_data):
        """Create recommendations section"""
        elements = []

        # Section header
        header = Paragraph("RECOMMENDATIONS", self.styles['SectionHeader'])
        elements.append(header)

        recommendations = [
            "Implement the suggested security actions from the conversation",
            "Review and update security policies based on identified threats",
            "Monitor the affected systems for any suspicious activity",
            "Conduct a comprehensive security assessment of the environment",
            "Ensure all security tools are properly configured and updated"
        ]

        for rec in recommendations:
            rec_para = Paragraph(f"• {rec}", self.styles['Normal'])
            elements.append(rec_para)
            elements.append(Spacer(1, 0.1*inch))

        return elements

    def _create_report_footer(self):
        """Create report footer"""
        elements = []

        elements.append(Spacer(1, 0.5*inch))

        # Footer text
        footer_text = """
        This report was generated automatically by the SOAR SOC Assistant.
        For questions or concerns, please contact the security operations team.
        """

        footer = Paragraph(footer_text, self.styles['Normal'])
        elements.append(footer)

        # Generation timestamp
        timestamp = Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", self.styles['Timestamp'])
        elements.append(timestamp)

        return elements
